import { existsSync } from 'node:fs'
import path from 'node:path'

export type StagingSmokeCategory =
  | 'PUBLIC'
  | 'MEMBER'
  | 'ADMIN'
  | 'SUPPORT'
  | 'BILLING'
  | 'EMAIL'
  | 'MIGRATION'
  | 'SECURITY'
  | 'CONTENT'

export type StagingSmokeEntry = {
  id: string
  category: StagingSmokeCategory
  routeOrOperation: string
  authRole: 'anonymous' | 'member' | 'pro-member' | 'admin' | 'operator'
  precondition: string
  smokeAction: string
  expectedResult: string
  evidenceToCapture: string
  automated: boolean
  providerBacked: boolean
  rollbackImplication: string
  blockerSeverity: 'low' | 'medium' | 'high' | 'critical'
  currentStatus: 'documented-unexecuted' | 'blocked-by-content-approval' | 'blocked-by-migration-approval'
  referencePaths: string[]
}

export const STAGING_SMOKE_MANIFEST: StagingSmokeEntry[] = [
  { id: 'public-landing', category: 'PUBLIC', routeOrOperation: 'GET /', authRole: 'anonymous', precondition: 'Approved staging build is deployed', smokeAction: 'Open the landing page and verify Free/Pro-only copy and primary CTA ownership.', expectedResult: 'Landing loads, pricing is coherent, and member entry points resolve to the portal.', evidenceToCapture: 'Landing screenshot with pricing and CTA.', automated: false, providerBacked: false, rollbackImplication: 'Stop release before any live provider or migration verification.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/page.tsx', 'e2e/public.spec.ts'] },
  { id: 'public-legal', category: 'PUBLIC', routeOrOperation: 'GET /privacy, /terms', authRole: 'anonymous', precondition: 'Approved staging build is deployed', smokeAction: 'Open canonical legal routes and confirm no legacy legal copy is visible.', expectedResult: 'Canonical legal routes load and legacy legal aliases do not become the primary surface.', evidenceToCapture: 'Canonical legal route screenshots.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if public legal copy is wrong.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/privacy/page.tsx', 'src/app/(frontend)/terms/page.tsx', 'e2e/public.spec.ts'] },
  { id: 'public-login', category: 'PUBLIC', routeOrOperation: 'GET /portal?mode=login', authRole: 'anonymous', precondition: 'Approved staging build is deployed', smokeAction: 'Open the member login shell and confirm the route stays under the portal boundary.', expectedResult: 'Login shell loads without leaking member or admin state.', evidenceToCapture: 'Portal login screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if anonymous auth entry is broken.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/page.tsx', 'e2e/auth-portal-admin.spec.ts'] },
  { id: 'public-register', category: 'PUBLIC', routeOrOperation: 'GET /register', authRole: 'anonymous', precondition: 'Approved staging build is deployed', smokeAction: 'Open the register compatibility route and confirm it points into the approved portal/member flow only.', expectedResult: 'Registration remains compatibility-only and does not introduce competing paid tiers.', evidenceToCapture: 'Register route screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if registration contradicts the Free/Pro contract.', blockerSeverity: 'medium', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/register/page.tsx', 'docs/ARCHITECTURE.md'] },
  { id: 'public-not-found', category: 'PUBLIC', routeOrOperation: 'GET unknown route', authRole: 'anonymous', precondition: 'Approved staging build is deployed', smokeAction: 'Open a known invalid public route.', expectedResult: 'Not-found behavior remains safe and does not expose framework or operator details.', evidenceToCapture: '404 screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if public error boundaries leak internals.', blockerSeverity: 'medium', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/not-found.tsx', 'e2e/public.spec.ts'] },
  { id: 'public-sitemap', category: 'PUBLIC', routeOrOperation: 'GET /sitemap.xml', authRole: 'anonymous', precondition: 'Approved staging build is deployed', smokeAction: 'Open the sitemap and confirm canonical launch routes only.', expectedResult: 'Sitemap includes approved routes and excludes operator-only or removed routes.', evidenceToCapture: 'Sitemap response excerpt or screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if canonical route ownership drifts.', blockerSeverity: 'medium', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/sitemap.ts', 'e2e/public.spec.ts'] },

  { id: 'member-login', category: 'MEMBER', routeOrOperation: 'Portal member login', authRole: 'member', precondition: 'Controlled member account is approved for smoke use', smokeAction: 'Sign in through the portal flow.', expectedResult: 'Member login succeeds without crossing into admin.', evidenceToCapture: 'Portal login success screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if member auth is broken.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/lib/auth/requirePortalMember.ts', 'e2e/auth-portal-admin.spec.ts'] },
  { id: 'member-portal-shell', category: 'MEMBER', routeOrOperation: 'GET /portal', authRole: 'member', precondition: 'Controlled member account is approved for smoke use', smokeAction: 'Open the member portal dashboard after login.', expectedResult: 'Portal shell renders with canonical navigation only.', evidenceToCapture: 'Portal dashboard screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if canonical member entry is broken.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/page.tsx', 'e2e/auth-portal-admin.spec.ts'] },
  { id: 'member-account', category: 'MEMBER', routeOrOperation: 'GET /portal/account', authRole: 'member', precondition: 'Controlled member account is approved for smoke use', smokeAction: 'Open the portal account surface.', expectedResult: 'Account view loads without exposing secrets or admin state.', evidenceToCapture: 'Portal account screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if account management is broken.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/[section]/page.tsx', 'scripts/portal_account_billing_parity.test.ts'] },
  { id: 'member-billing', category: 'MEMBER', routeOrOperation: 'GET /portal/billing', authRole: 'member', precondition: 'Controlled member account is approved for smoke use', smokeAction: 'Open the portal billing surface.', expectedResult: 'Billing overview loads and keeps ownership in the portal.', evidenceToCapture: 'Portal billing screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if billing ownership drifts.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/[section]/page.tsx', 'scripts/payload_member_billing_overview.test.ts'] },
  { id: 'member-courses', category: 'MEMBER', routeOrOperation: 'GET /portal/courses', authRole: 'member', precondition: 'Controlled member account is approved for smoke use', smokeAction: 'Open the canonical course index.', expectedResult: 'Course index loads only through the portal route tree.', evidenceToCapture: 'Portal courses screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if course routing or access breaks.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/courses/page.tsx', 'e2e/portal-courses-community.spec.ts'] },
  { id: 'member-lessons', category: 'MEMBER', routeOrOperation: 'GET /portal/courses/[courseSlug]/lessons/[lessonSlug]', authRole: 'member', precondition: 'Controlled entitled member account is approved for smoke use', smokeAction: 'Open one representative entitled lesson.', expectedResult: 'Lesson content and protected resources stay inside the approved entitlement boundary.', evidenceToCapture: 'Lesson screenshot and one protected-resource check note.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if protected content leaks or access fails.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/courses/[courseSlug]/lessons/[lessonSlug]/page.tsx', 'scripts/payload_lesson_resource_delivery.test.ts'] },
  { id: 'member-programme-preview', category: 'MEMBER', routeOrOperation: 'GET /portal/programme', authRole: 'member', precondition: 'Representative programme content is still unapproved', smokeAction: 'Open the programme route and confirm it remains an explicit preview.', expectedResult: 'Programme view stays preview-only and does not pretend approved content exists.', evidenceToCapture: 'Programme preview screenshot showing placeholder/preview state.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if programme content is misrepresented.', blockerSeverity: 'high', currentStatus: 'blocked-by-content-approval', referencePaths: ['src/app/(frontend)/portal/programme/page.tsx', 'scripts/course_programme_mvp.test.ts'] },
  { id: 'member-community-preview', category: 'MEMBER', routeOrOperation: 'GET /portal/community', authRole: 'member', precondition: 'Controlled member account is approved for smoke use', smokeAction: 'Open the community view and confirm the read-only preview boundary.', expectedResult: 'Community preview remains read-only where deferred interactions are not in first core go-live.', evidenceToCapture: 'Community screenshot and note on deferred interactions.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if community promises deferred functionality.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/community/page.tsx', 'scripts/community_preview_mvp.test.ts'] },
  { id: 'member-logout-session-expiry', category: 'MEMBER', routeOrOperation: 'Portal logout and expired-session flow', authRole: 'member', precondition: 'Controlled member account is approved for smoke use', smokeAction: 'Trigger logout and verify safe expired-session messaging.', expectedResult: 'Member logout succeeds and expired-session messaging does not leak details.', evidenceToCapture: 'Logout/expired-session screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if session boundaries are broken.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/page.tsx', 'e2e/auth-portal-admin.spec.ts'] },

  { id: 'admin-login', category: 'ADMIN', routeOrOperation: 'GET /admin', authRole: 'admin', precondition: 'Controlled admin account is approved for smoke use', smokeAction: 'Sign in through `/admin` only.', expectedResult: 'Admin login works without member-route crossover.', evidenceToCapture: 'Admin login screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if admin auth is broken.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(payload)/admin/[[...segments]]/page.tsx', 'scripts/payload_admin_branding.test.ts'] },
  { id: 'admin-denial-for-member', category: 'ADMIN', routeOrOperation: 'Member denial for /admin/review and operator routes', authRole: 'member', precondition: 'Controlled member account is approved for smoke use', smokeAction: 'Attempt direct operator navigation with a member session.', expectedResult: 'Operator routes fail closed for ordinary members.', evidenceToCapture: 'Denied-route screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if operator boundaries fail.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/admin/review/page.tsx', 'scripts/admin_review_access.test.ts'] },
  { id: 'admin-review-surface', category: 'ADMIN', routeOrOperation: 'Operator review surface', authRole: 'admin', precondition: 'Controlled admin account is approved for smoke use', smokeAction: 'Open the approved review surface and verify operational visibility only for admins.', expectedResult: 'Review surface loads for admins and remains inaccessible publicly.', evidenceToCapture: 'Admin review screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if admin review workflow is broken.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/admin_review_mvp.test.ts', 'scripts/payload_admin_dashboard.test.ts'] },
  { id: 'admin-payload-access', category: 'ADMIN', routeOrOperation: 'Payload admin collections', authRole: 'admin', precondition: 'Controlled admin account is approved for smoke use', smokeAction: 'Open representative Payload admin collections and dashboard cards.', expectedResult: 'Payload admin remains the canonical operator back office.', evidenceToCapture: 'Payload admin dashboard screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if admin operations are not accessible.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/payload_admin_dashboard.test.ts', 'docs/ARCHITECTURE.md'] },

  { id: 'support-valid-intake', category: 'SUPPORT', routeOrOperation: 'Valid /api/support request', authRole: 'anonymous', precondition: 'Support migration has been applied through the approved path', smokeAction: 'Submit one controlled support request after migration approval.', expectedResult: 'Request persists durably before success is shown.', evidenceToCapture: 'Support success screenshot and admin review note.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if support persistence fails.', blockerSeverity: 'critical', currentStatus: 'blocked-by-migration-approval', referencePaths: ['src/app/api/support/route.ts', 'scripts/support_intake_runtime.test.ts'] },
  { id: 'support-duplicate-intake', category: 'SUPPORT', routeOrOperation: 'Duplicate /api/support request', authRole: 'anonymous', precondition: 'Support migration has been applied through the approved path', smokeAction: 'Resubmit the same controlled support request within the dedupe window.', expectedResult: 'Duplicate request returns the same safe durable success contract.', evidenceToCapture: 'Duplicate submission result screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if dedupe fails.', blockerSeverity: 'high', currentStatus: 'blocked-by-migration-approval', referencePaths: ['scripts/support_intake_runtime.test.ts', 'e2e/support.spec.ts'] },
  { id: 'support-retryable-failure', category: 'SUPPORT', routeOrOperation: 'Retryable support queue failure', authRole: 'operator', precondition: 'Support migration has been applied through the approved path', smokeAction: 'Use the approved controlled failure path to verify retry wording and preserved request state.', expectedResult: 'Safe retry wording is shown and the persisted request remains reviewable.', evidenceToCapture: 'Retryable failure screenshot and review-state note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if queue failure loses persisted support data.', blockerSeverity: 'high', currentStatus: 'blocked-by-migration-approval', referencePaths: ['scripts/support_intake_runtime.test.ts', 'e2e/support.spec.ts'] },
  { id: 'support-review-state', category: 'SUPPORT', routeOrOperation: 'Support review state visibility', authRole: 'admin', precondition: 'Support migration has been applied through the approved path', smokeAction: 'Verify the persisted support request appears in the approved review path.', expectedResult: 'Review state remains explicit and operator-visible.', evidenceToCapture: 'Review-state screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if support review state is missing.', blockerSeverity: 'high', currentStatus: 'blocked-by-migration-approval', referencePaths: ['scripts/support_request_schema_contract.test.ts', 'docs/release/PROVIDER_VERIFICATION_RUNBOOK.md'] },
  { id: 'support-no-access-grant', category: 'SUPPORT', routeOrOperation: 'Support submission access boundary', authRole: 'operator', precondition: 'Support migration has been applied through the approved path', smokeAction: 'Verify the support workflow does not auto-grant Free or Pro access.', expectedResult: 'Support requests stay in review and do not change entitlements automatically.', evidenceToCapture: 'Operator note confirming no entitlement side effect.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if support grants access.', blockerSeverity: 'critical', currentStatus: 'blocked-by-migration-approval', referencePaths: ['scripts/pay_it_forward_mvp.test.ts', 'scripts/support_request_schema_contract.test.ts'] },
  { id: 'support-notification-queue', category: 'SUPPORT', routeOrOperation: 'Support notification queue state', authRole: 'admin', precondition: 'Support migration has been applied through the approved path', smokeAction: 'Verify queued notification state is visible and bounded after a controlled support request.', expectedResult: 'Queue state exists without direct-send claims.', evidenceToCapture: 'Queue-state screenshot or operator note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if notification state disappears.', blockerSeverity: 'high', currentStatus: 'blocked-by-migration-approval', referencePaths: ['scripts/payload_course_email_sender.test.ts', 'docs/release/PROVIDER_VERIFICATION_RUNBOOK.md'] },

  { id: 'billing-checkout-start', category: 'BILLING', routeOrOperation: 'GET /api/stripe/checkout?plan=pro&billing=monthly|annual', authRole: 'member', precondition: 'Controlled billing verification is approved', smokeAction: 'Start monthly and annual Pro checkout from the approved routes only.', expectedResult: 'Only supported Pro monthly and annual billing starts are accepted.', evidenceToCapture: 'Checkout-entry screenshots and request notes.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if unsupported billing starts succeed.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/api/stripe/checkout/route.ts', 'e2e/checkout-and-submissions.spec.ts'] },
  { id: 'billing-supported-plan-cadence', category: 'BILLING', routeOrOperation: 'Unsupported plan and cadence rejection', authRole: 'anonymous', precondition: 'Controlled billing verification is approved', smokeAction: 'Attempt invalid public plan or cadence values.', expectedResult: 'Invalid values fail safely and never start live checkout.', evidenceToCapture: 'Failure screenshots or logs.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if unsupported values are accepted.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/stripe_checkout_validation.test.ts', 'e2e/checkout-and-submissions.spec.ts'] },
  { id: 'billing-portal', category: 'BILLING', routeOrOperation: 'Billing portal handoff', authRole: 'member', precondition: 'Controlled member billing account is approved for smoke use', smokeAction: 'Open the billing portal from the portal billing route.', expectedResult: 'Billing portal remains member-owned and returns to the canonical portal billing page.', evidenceToCapture: 'Portal handoff evidence.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if portal customer ownership is wrong.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/payload_member_billing_portal.test.ts', 'scripts/billing-portal-token.test.ts'] },
  { id: 'billing-cancellation-request', category: 'BILLING', routeOrOperation: 'Cancellation request boundary', authRole: 'member', precondition: 'Controlled member billing account is approved for smoke use', smokeAction: 'Verify cancellation request wording and lifecycle for the approved commitment model.', expectedResult: 'Cancellation request stays within the approved 12-month commitment contract.', evidenceToCapture: 'Cancellation-control screenshot.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if cancellation behavior contradicts the contract.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['docs/decisions/M0-05_STRIPE_12_MONTH_COMMITMENT.md', 'scripts/member_checkout.test.ts'] },
  { id: 'billing-webhook-health', category: 'BILLING', routeOrOperation: 'Webhook projection readiness', authRole: 'operator', precondition: 'Controlled billing verification is approved', smokeAction: 'Confirm webhook projection readiness through approved non-live evidence or controlled staging health checks.', expectedResult: 'Webhook route and projection readiness remain canonical and bounded.', evidenceToCapture: 'Webhook readiness note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if billing state projection is not trustworthy.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/payload_course_stripe_shadow_sync.test.ts', 'scripts/billing_readiness_report.test.ts'] },
  { id: 'billing-failure-recovery', category: 'BILLING', routeOrOperation: 'Failure and recovery state handling', authRole: 'operator', precondition: 'Controlled billing verification is approved', smokeAction: 'Confirm payment-failure and recovery handling through approved evidence and controlled staging behavior.', expectedResult: 'Failure and recovery states remain safe and reversible.', evidenceToCapture: 'Failure/recovery evidence note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if failure recovery leaves wrong access state.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/billing_payment_communications.test.ts', 'scripts/billing_refund_dispute.test.ts'] },

  { id: 'email-queue-event', category: 'EMAIL', routeOrOperation: 'Queued email event creation', authRole: 'operator', precondition: 'Controlled provider verification is approved', smokeAction: 'Verify queue events are created before any live delivery action.', expectedResult: 'Queue event exists and no direct live send path is used.', evidenceToCapture: 'Queued email event note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if email queue ownership is broken.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/payload_course_email_sender.test.ts', 'docs/release/PROVIDER_VERIFICATION_RUNBOOK.md'] },
  { id: 'email-retry-behavior', category: 'EMAIL', routeOrOperation: 'Queued email retry behavior', authRole: 'operator', precondition: 'Controlled provider verification is approved', smokeAction: 'Confirm retry metadata is preserved for controlled failures.', expectedResult: 'Retry path exists without leaking provider detail.', evidenceToCapture: 'Retry-state note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if retry behavior is unsafe.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/payload_course_email_sender.test.ts', 'docs/release/PROVIDER_VERIFICATION_RUNBOOK.md'] },
  { id: 'email-redaction', category: 'EMAIL', routeOrOperation: 'Email redaction policy', authRole: 'operator', precondition: 'Controlled provider verification is approved', smokeAction: 'Confirm provider errors and message metadata remain redacted in UI, logs, and evidence.', expectedResult: 'No secret or private provider detail is exposed.', evidenceToCapture: 'Sanitized verification note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if provider data leaks.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/payload_course_email_sender.test.ts', 'docs/release/PROVIDER_VERIFICATION_RUNBOOK.md'] },
  { id: 'email-no-direct-send', category: 'EMAIL', routeOrOperation: 'No unapproved direct live send path', authRole: 'operator', precondition: 'Controlled provider verification is approved', smokeAction: 'Verify the operator sequence uses queue-first review and not a direct live send shortcut.', expectedResult: 'Live email remains separately approved and bounded.', evidenceToCapture: 'Operator note on approved send path.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if direct-send bypass exists.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['docs/release/PROVIDER_VERIFICATION_RUNBOOK.md', 'docs/client/PROVIDER_EMAIL_READINESS.md'] },

  { id: 'migration-schema-verification', category: 'MIGRATION', routeOrOperation: 'support_requests schema verification', authRole: 'operator', precondition: 'Migration has been applied through the approved path', smokeAction: 'Verify the `support_requests` table, indexes, defaults, and unique constraint.', expectedResult: 'Applied migration matches the reviewed schema contract exactly.', evidenceToCapture: 'Schema verification note.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if schema verification fails.', blockerSeverity: 'critical', currentStatus: 'blocked-by-migration-approval', referencePaths: ['docs/release/SUPPORT_REQUESTS_MIGRATION_RUNBOOK.md', 'prisma/migrations/20260712_151700_add_support_requests/migration.sql'] },
  { id: 'migration-post-apply-readiness', category: 'MIGRATION', routeOrOperation: 'Post-migration application readiness', authRole: 'operator', precondition: 'Migration has been applied through the approved path', smokeAction: 'Run post-apply route and schema verification from the migration runbook.', expectedResult: 'Support route and schema validations still pass after apply.', evidenceToCapture: 'Post-apply verification note.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if the app is not ready after apply.', blockerSeverity: 'critical', currentStatus: 'blocked-by-migration-approval', referencePaths: ['docs/release/SUPPORT_REQUESTS_MIGRATION_RUNBOOK.md', 'scripts/support_request_schema_contract.test.ts'] },
  { id: 'migration-rollback-trigger', category: 'MIGRATION', routeOrOperation: 'Rollback trigger review', authRole: 'operator', precondition: 'Migration approval and backup evidence exist', smokeAction: 'Review rollback trigger criteria before and after the maintenance window.', expectedResult: 'Rollback decision points are explicit before live execution.', evidenceToCapture: 'Rollback trigger review note.', automated: false, providerBacked: false, rollbackImplication: 'Release cannot continue if rollback criteria are unclear.', blockerSeverity: 'critical', currentStatus: 'blocked-by-migration-approval', referencePaths: ['docs/release/SUPPORT_REQUESTS_MIGRATION_RUNBOOK.md', 'docs/client/MIGRATION_REHEARSAL_RUNBOOK.md'] },

  { id: 'security-no-learn', category: 'SECURITY', routeOrOperation: 'Removed member namespace invariant', authRole: 'anonymous', precondition: 'Approved staging build is deployed', smokeAction: 'Verify the removed legacy member namespace does not resolve as an active route.', expectedResult: 'Removed member namespace remains absent.', evidenceToCapture: 'Denied-route screenshot or note.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if removed member routes return.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/no_legacy_learn_namespace.test.ts', 'e2e/auth-portal-admin.spec.ts'] },
  { id: 'security-guarded-writes', category: 'SECURITY', routeOrOperation: 'Guarded write routes', authRole: 'anonymous', precondition: 'Approved staging build is deployed', smokeAction: 'Confirm guarded write endpoints still reject invalid method, content-type, and origin scenarios.', expectedResult: 'Public write boundaries fail closed.', evidenceToCapture: 'Guarded-write verification note.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if write guards regress.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/public_request_guard.test.ts', 'e2e/checkout-and-submissions.spec.ts'] },
  { id: 'security-admin-denial', category: 'SECURITY', routeOrOperation: 'Admin denial', authRole: 'member', precondition: 'Approved staging build is deployed', smokeAction: 'Verify admin/operator routes remain denied to anonymous and ordinary members.', expectedResult: 'Operator routes fail closed.', evidenceToCapture: 'Denied-route screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if admin denial regresses.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/admin_review_access.test.ts', 'e2e/auth-portal-admin.spec.ts'] },
  { id: 'security-no-secrets', category: 'SECURITY', routeOrOperation: 'No secrets in responses or logs', authRole: 'operator', precondition: 'Approved staging build is deployed', smokeAction: 'Verify representative support, billing, and auth paths do not leak secrets in visible UI or approved logs.', expectedResult: 'Visible responses and approved evidence remain redacted.', evidenceToCapture: 'Sanitized redaction note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if sensitive data leaks.', blockerSeverity: 'critical', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/support_intake_runtime.test.ts', 'scripts/payload_course_email_sender.test.ts'] },
  { id: 'security-provider-errors', category: 'SECURITY', routeOrOperation: 'Provider error redaction', authRole: 'operator', precondition: 'Controlled provider verification is approved', smokeAction: 'Verify provider failures remain bounded and do not expose raw provider errors.', expectedResult: 'Provider failures remain safe for operators and members.', evidenceToCapture: 'Sanitized provider-failure note.', automated: false, providerBacked: true, rollbackImplication: 'Hold release if raw provider errors surface.', blockerSeverity: 'high', currentStatus: 'documented-unexecuted', referencePaths: ['scripts/payload_member_email_verification_integration.test.ts', 'docs/release/PROVIDER_VERIFICATION_RUNBOOK.md'] },

  { id: 'content-programme-preview', category: 'CONTENT', routeOrOperation: 'Programme preview truth', authRole: 'member', precondition: 'Representative programme content is still unapproved', smokeAction: 'Verify programme content remains clearly marked preview-only.', expectedResult: 'No fake approved content is implied.', evidenceToCapture: 'Programme preview screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if unapproved content is presented as final.', blockerSeverity: 'high', currentStatus: 'blocked-by-content-approval', referencePaths: ['docs/PREVIEW_RELEASE_READINESS.md', 'scripts/course_programme_mvp.test.ts'] },
  { id: 'content-canonical-navigation', category: 'CONTENT', routeOrOperation: 'Canonical portal navigation', authRole: 'member', precondition: 'Approved staging build is deployed', smokeAction: 'Verify canonical portal navigation labels and routes remain aligned to the current product contract.', expectedResult: 'Portal navigation stays coherent across courses, programme, billing, support, and community.', evidenceToCapture: 'Portal navigation screenshot.', automated: false, providerBacked: false, rollbackImplication: 'Hold release if navigation contradicts product boundaries.', blockerSeverity: 'medium', currentStatus: 'documented-unexecuted', referencePaths: ['src/app/(frontend)/portal/page.tsx', 'e2e/auth-portal-admin.spec.ts'] },
  { id: 'content-no-fake-approval', category: 'CONTENT', routeOrOperation: 'No fabricated approved content claims', authRole: 'operator', precondition: 'Representative programme content is still unapproved', smokeAction: 'Verify docs and staging smoke output keep the approval blocker explicit.', expectedResult: 'Repository and operator evidence continue to treat programme content as blocked.', evidenceToCapture: 'Operator note referencing the blocker.', automated: true, providerBacked: false, rollbackImplication: 'Hold release if docs imply nonexistent approval.', blockerSeverity: 'high', currentStatus: 'blocked-by-content-approval', referencePaths: ['docs/PREVIEW_RELEASE_READINESS.md', 'scripts/core_go_live_readiness.test.ts'] },
]

const REQUIRED_CATEGORIES: ReadonlyArray<StagingSmokeCategory> = [
  'PUBLIC',
  'MEMBER',
  'ADMIN',
  'SUPPORT',
  'BILLING',
  'EMAIL',
  'MIGRATION',
  'SECURITY',
  'CONTENT',
]

const FORBIDDEN_PATTERNS = [
  /https:\/\/|http:\/\//i,
  /\bprisma migrate\b/i,
  /\bdeploy\b/i,
  /\bpayload:email:send\b/i,
  /\bcurl\b/i,
  /\bwget\b/i,
  /\bstripe:check-products\b/i,
]

export function validateStagingSmokeManifest(cwd = process.cwd()): { ok: boolean; errors: string[] } {
  const errors: string[] = []
  const ids = STAGING_SMOKE_MANIFEST.map((entry) => entry.id)
  if (new Set(ids).size !== ids.length) errors.push('duplicate_ids')

  for (const category of REQUIRED_CATEGORIES) {
    if (!STAGING_SMOKE_MANIFEST.some((entry) => entry.category === category)) {
      errors.push(`missing_category:${category}`)
    }
  }

  for (const entry of STAGING_SMOKE_MANIFEST) {
    for (const field of [
      entry.id,
      entry.category,
      entry.routeOrOperation,
      entry.authRole,
      entry.precondition,
      entry.smokeAction,
      entry.expectedResult,
      entry.evidenceToCapture,
      entry.rollbackImplication,
      entry.blockerSeverity,
      entry.currentStatus,
    ]) {
      if (!String(field).trim()) errors.push(`missing_field:${entry.id}`)
    }
    if (entry.referencePaths.length === 0) errors.push(`missing_references:${entry.id}`)
    for (const ref of entry.referencePaths) {
      if (!existsSync(path.join(cwd, ref))) errors.push(`missing_reference:${entry.id}:${ref}`)
    }
    const combined = [entry.routeOrOperation, entry.precondition, entry.smokeAction, entry.expectedResult, entry.evidenceToCapture].join('\n')
    for (const pattern of FORBIDDEN_PATTERNS) {
      if (pattern.test(combined)) errors.push(`forbidden_pattern:${entry.id}:${pattern}`)
    }
  }

  if (!STAGING_SMOKE_MANIFEST.some((entry) => entry.category === 'CONTENT' && entry.currentStatus === 'blocked-by-content-approval')) {
    errors.push('programme_preview_blocker_missing')
  }
  if (!STAGING_SMOKE_MANIFEST.some((entry) => entry.providerBacked && entry.currentStatus === 'documented-unexecuted')) {
    errors.push('provider_checks_not_documented_unexecuted')
  }

  return { ok: errors.length === 0, errors }
}
