'use client'

import type { DefaultNodeTypes, SerializedBlockNode } from '@payloadcms/richtext-lexical'
import type { SerializedEditorState } from '@payloadcms/richtext-lexical/lexical'
import {
  type JSXConvertersFunction,
  RichText,
} from '@payloadcms/richtext-lexical/react'

import { ManagedBunnyVideoPlayer } from '@/components/portal/ManagedBunnyVideoPlayer'
import { restoreLegacyLessonImagePlaceholders } from '@/lib/payloadContent/legacyLessonMedia'
import type {
  BunnyVideoBlockFields,
  LegacyHTMLBlockFields,
} from '@/richtext/LegacyMigrationBlocks'

type LessonNodeTypes =
  | DefaultNodeTypes
  | SerializedBlockNode<BunnyVideoBlockFields | LegacyHTMLBlockFields>

function createLessonConverters(lessonSlug: string): JSXConvertersFunction<LessonNodeTypes> {
  return ({ defaultConverters }) => ({
    ...defaultConverters,
    blocks: {
      ...(defaultConverters.blocks ?? {}),
      legacyHTML: ({ node }) => {
        const safeHtml = restoreLegacyLessonImagePlaceholders(node.fields.safeHtml?.trim() ?? '')
        if (!safeHtml) {
          return (
            <aside className='jpv-notice mt-5' data-legacy-html-preserved='true'>
              <p className='text-sm font-semibold text-jpv-ink'>Legacy content preserved</p>
              <p className='mt-1 text-sm text-jpv-muted'>
                This source fragment was retained but is hidden because it cannot be rendered safely yet.
              </p>
            </aside>
          )
        }

        return (
          <div
            className='jpv-rich-text legacy-html-fragment my-5'
            data-legacy-html-preserved='true'
            // safeHtml is generated by the migration sanitizer; never render node.fields.html directly.
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: safeHtml }}
          />
        )
      },
      bunnyVideo: ({ node }) => (
        <div className='my-6' data-inline-bunny-guid={node.fields.videoGuid}>
          <ManagedBunnyVideoPlayer
            containerClassName='mx-auto max-w-4xl'
            slug={lessonSlug}
            target='lesson'
            title={node.fields.title ?? 'Lesson video'}
            videoGuid={node.fields.videoGuid}
          />
        </div>
      ),
    },
  })
}

export function LegacyLessonRichText({
  data,
  lessonSlug,
}: {
  data: SerializedEditorState
  lessonSlug: string
}) {
  return (
    <div className='jpv-rich-text lesson-body mx-auto mt-8 max-w-4xl text-sm leading-7 text-jpv-ink [&_h2]:mb-2 [&_h2]:mt-6 [&_h2]:text-xl [&_h2]:font-semibold [&_h3]:mb-2 [&_h3]:mt-4 [&_h3]:text-lg [&_h3]:font-semibold [&_a]:text-jpv-brand-deep [&_a]:underline [&_a]:underline-offset-4 [&_blockquote]:border-l-4 [&_blockquote]:border-jpv-border [&_blockquote]:pl-4 [&_blockquote]:italic [&_img]:my-5 [&_img]:h-auto [&_img]:max-w-full [&_li]:ml-4 [&_li]:list-disc [&_ol_li]:list-decimal [&_p]:mb-3'>
      <RichText converters={createLessonConverters(lessonSlug)} data={data} />
    </div>
  )
}
