import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

import { RELEASE_TEST_MANIFEST } from './release/releaseTestManifest'

function commandOf(id: string): string | undefined {
  const entry = RELEASE_TEST_MANIFEST.find((item) => item.id === id)
  if (!entry) return undefined
  return [entry.command.executable, ...entry.command.args].join(' ')
}

function main(): void {
  const releaseCount = RELEASE_TEST_MANIFEST.filter((entry) => entry.requirement === 'required').length
  const previewReadiness = readFileSync('docs/PREVIEW_RELEASE_READINESS.md', 'utf8')
  const roadmap = readFileSync('docs/client/ROADMAP_PROGRESS_STATUS.md', 'utf8')
  const operatorHandoff = readFileSync('docs/client/OPERATOR_HANDOFF_SUMMARY.md', 'utf8')
  const architecture = readFileSync('docs/ARCHITECTURE.md', 'utf8')
  const migrationRunbook = readFileSync('docs/release/SUPPORT_REQUESTS_MIGRATION_RUNBOOK.md', 'utf8')
  const providerRunbook = readFileSync('docs/release/PROVIDER_VERIFICATION_RUNBOOK.md', 'utf8')
  const goNoGoChecklist = readFileSync('docs/release/GO_NO_GO_CHECKLIST.md', 'utf8')
  const packageJson = JSON.parse(readFileSync('package.json', 'utf8')) as { scripts?: Record<string, string> }

  assert.match(architecture, /Canonical `\/portal` account, course, community, partner, support, and billing experience/)
  assert.match(architecture, /\| Admin CMS \| Payload \|/)

  const combined = [previewReadiness, roadmap, operatorHandoff, architecture].join('\n')

  assert.match(combined, /feature\/course-branding-and-preview/)
  assert.match(combined, /\/portal/)
  assert.match(combined, /\/admin/)
  const removedMemberNamespace = new RegExp(`/${'learn'}(?:/|\\b)`)
  assert.doesNotMatch(combined, removedMemberNamespace)

  assert.equal(commandOf('member.portal-mvp'), 'pnpm exec tsx scripts/member_portal_mvp.test.ts')
  assert.equal(commandOf('routes.no-legacy-learn-namespace'), 'pnpm exec tsx scripts/no_legacy_learn_namespace.test.ts')
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.core-go-live-readiness'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.command.args.join(' ') === 'exec tsx scripts/core_go_live_readiness.test.ts'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.migration-preflight'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.decision-manifest'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.decision-runner'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.decision-readiness'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.core-go-live-decision'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'migration.rehearsal-runner'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.migration-rehearsal-markdown'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.provider-simulation-contract'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.provider-simulation'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.simulated-smoke-contract'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.rollback-checklist'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.staging-smoke-manifest'))
  assert.ok(RELEASE_TEST_MANIFEST.some((entry) => entry.id === 'evidence.release-evidence-generator'))

  assert.equal(packageJson.scripts?.['staging:migration-preflight'], 'tsx scripts/release/stagingMigrationPreflight.ts')
  assert.equal(packageJson.scripts?.['staging:migration-status'], 'tsx scripts/release/buildStagingMigrationStatus.ts')
  assert.equal(packageJson.scripts?.['production:migration-status:read-only'], 'tsx scripts/release/verifyProductionMigrationStatus.ts')
  assert.equal(packageJson.scripts?.['staging:migration-rehearsal'], 'tsx scripts/release/migrationRehearsal.ts')
  assert.equal(packageJson.scripts?.['staging:migration-rehearsal:evidence'], 'tsx scripts/release/buildMigrationRehearsalEvidence.ts')
  assert.equal(packageJson.scripts?.['staging:decision-readiness'], 'tsx scripts/release/runDecisionReadiness.ts')
  assert.equal(packageJson.scripts?.['staging:provider-simulation'], 'tsx scripts/release/providerSimulation.ts')
  assert.equal(packageJson.scripts?.['staging:smoke-plan'], 'tsx scripts/release/printStagingSmokePlan.ts')
  assert.equal(packageJson.scripts?.['staging:smoke-simulated'], 'tsx scripts/release/simulatedStagingSmoke.ts')
  assert.equal(packageJson.scripts?.['release:evidence:dry-run'], 'tsx scripts/release/buildReleaseEvidence.ts')

  assert.match(migrationRunbook, /Support Requests Migration Runbook/)
  assert.match(migrationRunbook, /pnpm staging:migration-preflight/)
  assert.match(migrationRunbook, /pnpm staging:migration-rehearsal/)
  assert.match(migrationRunbook, /pnpm staging:migration-rehearsal:evidence/)
  assert.match(migrationRunbook, /\.\/node_modules\/\.bin\/prisma migrate deploy --schema=prisma\/system\.prisma/)
  assert.match(migrationRunbook, /Primary rollback strategy:\s+restore-based/i)
  assert.match(providerRunbook, /Provider Verification Runbook/)
  assert.match(providerRunbook, /pnpm staging:provider-simulation/)
  assert.match(providerRunbook, /pnpm staging:smoke-plan/)
  assert.match(providerRunbook, /pnpm staging:smoke-simulated/)
  assert.match(providerRunbook, /Provider verification is documented but unexecuted\./)
  assert.match(goNoGoChecklist, /Default decision state: `NO-GO`/)
  assert.match(goNoGoChecklist, /Decision-readiness prerequisite: `pnpm staging:decision-readiness`/)
  assert.match(goNoGoChecklist, /pnpm staging:migration-preflight/)
  assert.match(goNoGoChecklist, /pnpm staging:migration-rehearsal/)
  assert.match(goNoGoChecklist, /pnpm staging:provider-simulation/)
  assert.match(goNoGoChecklist, /pnpm staging:smoke-plan/)
  assert.match(goNoGoChecklist, /pnpm staging:smoke-simulated/)
  assert.match(goNoGoChecklist, /pnpm release:evidence:dry-run/)
  assert.match(goNoGoChecklist, /DECISION-READY, EXTERNAL APPROVALS PENDING/)
  assert.match(goNoGoChecklist, /migration applied \| pending until executed/i)
  assert.match(goNoGoChecklist, /provider verification \| pending until executed/i)
  assert.match(goNoGoChecklist, /staging smoke \| pending until executed/i)

  for (const doc of [previewReadiness, roadmap, operatorHandoff]) {
    assert.match(doc, /36\/36(?:.*Payload migrations)? applied|35\/35.*registration|35 canonical Payload migration registrations|36 canonical Payload migration registrations|35 Payload migrations applied|canonical 29-name Payload registry/i)
    assert.match(doc, /not.*applied database state|not database-applied state|not evidence that those migrations were applied/i)
    assert.match(doc, /staging:migration-status/)
    assert.match(doc, /31215369413/)
    assert.match(doc, /no real source (?:export|import)|no real source export.*no real source import/is)
    assert.match(doc, /programme remains preview-only|programme content is still blocked|representative programme content/i)
    assert.match(doc, /Provider\/email .*pending|provider\/email .*not executed|provider\/email verification/i)
    assert.match(doc, /staging smoke .*pending|staging smoke .*not executed/i)
    assert.match(doc, /account-action/i)
    assert.match(doc, /reservation\/finalization/i)
    assert.match(doc, /go\/no-go/i)
  }

  assert.match(previewReadiness, /STAGING MIGRATION COMPLETE/)
  assert.match(previewReadiness, /LAUNCH-SCOPE REPOSITORY IMPLEMENTATION COMPLETE — FINAL PRE-MIGRATION CLOSURE IN PROGRESS/)
  assert.doesNotMatch(previewReadiness, /STAGING IMPLEMENTATION AND ACCEPTANCE COMPLETE/)
  assert.match(previewReadiness, /9c045fa5a5c327014c20fe9377f7d5368b550573/)
  assert.match(previewReadiness, /30853006495/)
  assert.match(previewReadiness, /M2-01.*post-core/i)
  assert.match(previewReadiness, new RegExp(`pnpm test:release.*${releaseCount}\\/${releaseCount}`, 'i'))
  assert.match(previewReadiness, /pnpm test:e2e.*188 collected.*148 passed/i)
  assert.match(previewReadiness, /pnpm staging:decision-readiness/i)
  assert.match(previewReadiness, /pnpm test:release:full/)
  assert.match(previewReadiness, /pnpm staging:static-preflight/)
  assert.match(previewReadiness, /PRE-APPLY EVIDENCE CLEAN — FINAL EXACT-SHA PLAN AND MIGRATION AUTHORIZATION PENDING/)
  assert.match(previewReadiness, /pnpm staging:migration-preflight/)
  assert.match(previewReadiness, /pnpm staging:migration-rehearsal/)
  assert.match(previewReadiness, /pnpm staging:provider-simulation/)
  assert.match(previewReadiness, /pnpm staging:smoke-plan/)
  assert.match(previewReadiness, /pnpm staging:smoke-simulated/)
  assert.match(previewReadiness, /pnpm release:evidence:dry-run/)
  assert.match(previewReadiness, /PROGRAMME_CONTENT_INTAKE_TEMPLATE\.md/)
  assert.match(previewReadiness, /PROGRAMME_CONTENT_APPROVAL_RECORD\.md/)
  assert.match(previewReadiness, /content:programme:validate/)
  assert.match(previewReadiness, /content:programme:acceptance/)
  assert.match(previewReadiness, /content:programme:import-plan/)
  assert.match(previewReadiness, /3 moderate/)
  assert.doesNotMatch(previewReadiness, /READY FOR PRODUCTION|production-ready|go-live complete/i)

  assert.match(roadmap, /STAGING MIGRATION COMPLETE|LAUNCH-SCOPE REPOSITORY IMPLEMENTATION COMPLETE/)
  assert.match(roadmap, /LAUNCH-SCOPE REPOSITORY IMPLEMENTATION COMPLETE — FINAL PRE-MIGRATION CLOSURE IN PROGRESS/)
  assert.match(roadmap, /DECISION-READY, EXTERNAL APPROVALS PENDING/i)
  assert.match(roadmap, /M0-01 through M0-09/)
  assert.match(roadmap, /M1-01 through M1-06/)
  assert.match(roadmap, /9c045fa5a5c327014c20fe9377f7d5368b550573/)

  assert.match(operatorHandoff, /9c045fa5a5c327014c20fe9377f7d5368b550573/)
  assert.match(operatorHandoff, new RegExp(String.raw`Deterministic release gate: \`pnpm test:release\` \(\`${releaseCount}\/${releaseCount}\`\)`))
  assert.match(operatorHandoff, /Launch browser E2E: `pnpm test:e2e` \(Playwright: 188 collected, 148 passed/)
  assert.match(operatorHandoff, /pnpm staging:decision-readiness/)
  assert.match(operatorHandoff, /DECISION-READY, EXTERNAL APPROVALS PENDING/)
  assert.match(operatorHandoff, /M2-01.*deferred post-core/i)
  assert.match(operatorHandoff, /pnpm staging:migration-preflight/)
  assert.match(operatorHandoff, /pnpm staging:migration-rehearsal/)
  assert.match(operatorHandoff, /pnpm staging:provider-simulation/)
  assert.match(operatorHandoff, /pnpm staging:smoke-plan/)
  assert.match(operatorHandoff, /pnpm staging:smoke-simulated/)
  assert.match(operatorHandoff, /pnpm release:evidence:dry-run/)
  assert.match(operatorHandoff, /ROLLBACK_EVIDENCE_CHECKLIST\.md/)
  assert.match(operatorHandoff, /PROGRAMME_CONTENT_INTAKE_TEMPLATE\.md/)
  assert.match(operatorHandoff, /PROGRAMME_CONTENT_APPROVAL_RECORD\.md/)
  assert.match(operatorHandoff, /content:programme:validate/)
  assert.match(operatorHandoff, /content:programme:acceptance/)
  assert.match(operatorHandoff, /content:programme:import-plan/)

  console.log('core_go_live_readiness.test.ts passed')
}

main()
