import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const requirePortalMember = readFileSync('src/lib/auth/requirePortalMember.ts', 'utf8')
const portalPage = readFileSync('src/app/(frontend)/portal/page.tsx', 'utf8')
const portalLayout = readFileSync('src/app/(frontend)/portal/layout.tsx', 'utf8')
const providers = readFileSync('src/components/providers.tsx', 'utf8')
const portalShell = readFileSync('src/components/portal/PortalShell.tsx', 'utf8')
const payloadConfig = readFileSync('src/payload.config.ts', 'utf8')
const loginPage = readFileSync('src/app/(frontend)/login/page.tsx', 'utf8')
const registerRoute = readFileSync('src/app/(frontend)/register/route.ts', 'utf8')
const verificationHttp = readFileSync('src/lib/auth/memberEmailVerificationHttp.ts', 'utf8')
const emailChangeComplete = readFileSync('src/app/api/member-email-change/complete/route.ts', 'utf8')
const passwordReset = readFileSync('src/app/api/member-password/reset/route.ts', 'utf8')
const memberSetup = readFileSync('src/app/api/member-invitations/complete/route.ts', 'utf8')
const memberLogin = readFileSync('src/components/auth/MemberLoginForm.tsx', 'utf8')
const memberSession = readFileSync('src/app/api/member-session/route.ts', 'utf8')
const payloadSessionMapping = readFileSync('src/lib/auth/payloadSessionMapping.ts', 'utf8')
const portalAccess = readFileSync('src/lib/auth/requirePortalAccess.ts', 'utf8')
const adminMemberIdentity = readFileSync('src/lib/auth/adminMemberIdentity.ts', 'utf8')
const adminModeContext = readFileSync('src/components/portal/AdminModeContext.tsx', 'utf8')
const removedMemberNamespacePattern = new RegExp(`redirect\\('${'/' + 'learn'}`)

assert.match(requirePortalMember, /\/portal\?mode=login&next=/)
assert.doesNotMatch(requirePortalMember, /redirect\(`\/login/)

assert.match(portalPage, /firstValue\(params\?\.mode\) === 'login'/)
assert.match(portalPage, /MemberLoginForm/)
assert.match(portalPage, /MemberVerificationResendForm/)
assert.match(portalPage, /Choose membership/)
assert.match(portalPage, /Forgot password/)
assert.doesNotMatch(portalPage, /the administrator sign-in/)
assert.match(portalPage, /mode\) === 'register'/)
assert.match(portalPage, /redirect\('\/upgrade'\)/)
assert.doesNotMatch(portalPage, /Create free account|New Free accounts/)
assert.doesNotMatch(portalLayout, /requirePortalMember\('/)
assert.match(portalLayout, /cachedResolvePayloadRequestSession|resolvePayloadRequestSession/)
assert.match(portalLayout, /showLogout/)

assert.match(loginPage, /new URLSearchParams\(\{ mode: 'login' \}\)/)
assert.match(loginPage, /redirect\(`\/portal/)
assert.doesNotMatch(loginPage, /MemberLoginForm/)

assert.match(registerRoute, /410|Gone/)
assert.match(registerRoute, /Registration is permanently disabled/)
assert.match(registerRoute, /exclusive.*Checkout/)
assert.match(registerRoute, /\/upgrade/)
assert.doesNotMatch(registerRoute, /MemberRegistrationForm|Create free account/)
assert.doesNotMatch(registerRoute, removedMemberNamespacePattern)

assert.match(verificationHttp, /new URL\('\/portal'/)
assert.match(verificationHttp, /mode', 'login'/)
assert.match(emailChangeComplete, /status: 410/)
assert.match(emailChangeComplete, /email_change_disabled/)
assert.doesNotMatch(emailChangeComplete, /completeMemberEmailChange|buildMemberEmailChangeLoginResultUrl/)
assert.match(passwordReset, /destination: '\/portal\?mode=login'/)
assert.match(memberSetup, /destination: '\/portal\?mode=login'/)

assert.match(memberLogin, /loginRequest\('payload_users'\)/)
assert.match(memberLogin, /loginRequest\('payload_members'\)/)
assert.match(memberSession, /session\.administratorId/)
assert.match(memberSession, /resolveMemberDestination\(requestedDestination\)/)
assert.match(payloadSessionMapping, /ADMIN_COLLECTION = 'payload_users'/)
assert.match(portalAccess, /resolveAdministratorMemberIdentity/)
assert.doesNotMatch(portalAccess, /ensureAdministratorMemberIdentity/)
assert.doesNotMatch(requirePortalMember, /ensureAdministratorMemberIdentity/)
assert.match(adminMemberIdentity, /resolveAdministratorMemberIdentity/)
assert.match(adminMemberIdentity, /limit: 2/)
assert.match(adminMemberIdentity, /source: 'ambiguous'/)
assert.match(portalAccess, /session\.administratorId && !session\.unresolvedCollection/)
assert.match(adminModeContext, /const \[adminModeOn, setAdminModeOn\] = useState\(isAdmin\)/)
assert.match(adminModeContext, /toggleAdminMode/)

assert.doesNotMatch(portalLayout, /defaultTheme=|enableSystem=|forcedTheme=|storageKey=/)
assert.match(portalLayout, /showThemeToggle=\{isAuthenticated\}/)
assert.match(providers, /PublicThemeReset/)
assert.match(providers, /document\.documentElement\.classList\.remove\('dark'\)/)
assert.match(providers, /<Suspense fallback=\{null\}>/)
assert.match(portalShell, /ThemeProvider/)
assert.match(portalShell, /allowPortalTheme = showThemeToggle && !isPortalLogin/)
assert.doesNotMatch(portalShell, /storageKey=/)
assert.match(readFileSync('src/components/portal/PortalTopBar.tsx', 'utf8'), /!isPortalLogin/)
assert.match(portalPage, /Admin Mode starts on/)
assert.match(portalPage, /Member or administrator sign in/)
assert.match(portalPage, /turn it off or on from the top bar/)
assert.match(payloadConfig, /theme: 'light'/)

console.log('payload_member_auth_architecture.test.ts passed')
