/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    payload_users: PayloadUserAuthOperations;
    payload_members: PayloadMemberAuthOperations;
  };
  blocks: {};
  collections: {
    payload_users: PayloadUser;
    payload_media: PayloadMedia;
    payload_pages: PayloadPage;
    payload_posts: PayloadPost;
    payload_categories: PayloadCategory;
    payload_courses: PayloadCourse;
    payload_course_modules: PayloadCourseModule;
    payload_lessons: PayloadLesson;
    payload_course_access_preview: PayloadCourseAccessPreview;
    payload_members: PayloadMember;
    payload_member_profiles: PayloadMemberProfile;
    payload_member_security_events: PayloadMemberSecurityEvent;
    payload_member_verification_tokens: PayloadMemberVerificationToken;
    payload_private_media: PayloadPrivateMedia;
    payload_lesson_resources: PayloadLessonResource;
    payload_course_enrollments: PayloadCourseEnrollment;
    payload_lesson_progress: PayloadLessonProgress;
    payload_access_groups: PayloadAccessGroup;
    payload_access_policies: PayloadAccessPolicy;
    payload_access_grants: PayloadAccessGrant;
    payload_entitlement_events: PayloadEntitlementEvent;
    payload_affiliates: PayloadAffiliate;
    payload_affiliate_referrals: PayloadAffiliateReferral;
    payload_affiliate_commissions: PayloadAffiliateCommission;
    payload_partner_affiliates: PayloadPartnerAffiliate;
    payload_partner_applications: PayloadPartnerApplication;
    payload_partner_events: PayloadPartnerEvent;
    payload_billing_accounts: PayloadBillingAccount;
    payload_subscriptions: PayloadSubscription;
    payload_payments: PayloadPayment;
    payload_stripe_events: PayloadStripeEvent;
    payload_billing_actions: PayloadBillingAction;
    payload_contacts: PayloadContact;
    payload_crm_tags: PayloadCrmTag;
    payload_contact_tags: PayloadContactTag;
    payload_contact_notes: PayloadContactNote;
    payload_email_templates: PayloadEmailTemplate;
    payload_email_events: PayloadEmailEvent;
    payload_admin_notifications: PayloadAdminNotification;
    payload_member_groups: PayloadMemberGroup;
    payload_spaces: PayloadSpace;
    payload_space_memberships: PayloadSpaceMembership;
    payload_space_posts: PayloadSpacePost;
    payload_space_comments: PayloadSpaceComment;
    payload_space_files: PayloadSpaceFile;
    payload_chat_threads: PayloadChatThread;
    payload_chat_messages: PayloadChatMessage;
    payload_audit_events: PayloadAuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    payload_users: PayloadUsersSelect<false> | PayloadUsersSelect<true>;
    payload_media: PayloadMediaSelect<false> | PayloadMediaSelect<true>;
    payload_pages: PayloadPagesSelect<false> | PayloadPagesSelect<true>;
    payload_posts: PayloadPostsSelect<false> | PayloadPostsSelect<true>;
    payload_categories: PayloadCategoriesSelect<false> | PayloadCategoriesSelect<true>;
    payload_courses: PayloadCoursesSelect<false> | PayloadCoursesSelect<true>;
    payload_course_modules: PayloadCourseModulesSelect<false> | PayloadCourseModulesSelect<true>;
    payload_lessons: PayloadLessonsSelect<false> | PayloadLessonsSelect<true>;
    payload_course_access_preview: PayloadCourseAccessPreviewSelect<false> | PayloadCourseAccessPreviewSelect<true>;
    payload_members: PayloadMembersSelect<false> | PayloadMembersSelect<true>;
    payload_member_profiles: PayloadMemberProfilesSelect<false> | PayloadMemberProfilesSelect<true>;
    payload_member_security_events: PayloadMemberSecurityEventsSelect<false> | PayloadMemberSecurityEventsSelect<true>;
    payload_member_verification_tokens: PayloadMemberVerificationTokensSelect<false> | PayloadMemberVerificationTokensSelect<true>;
    payload_private_media: PayloadPrivateMediaSelect<false> | PayloadPrivateMediaSelect<true>;
    payload_lesson_resources: PayloadLessonResourcesSelect<false> | PayloadLessonResourcesSelect<true>;
    payload_course_enrollments: PayloadCourseEnrollmentsSelect<false> | PayloadCourseEnrollmentsSelect<true>;
    payload_lesson_progress: PayloadLessonProgressSelect<false> | PayloadLessonProgressSelect<true>;
    payload_access_groups: PayloadAccessGroupsSelect<false> | PayloadAccessGroupsSelect<true>;
    payload_access_policies: PayloadAccessPoliciesSelect<false> | PayloadAccessPoliciesSelect<true>;
    payload_access_grants: PayloadAccessGrantsSelect<false> | PayloadAccessGrantsSelect<true>;
    payload_entitlement_events: PayloadEntitlementEventsSelect<false> | PayloadEntitlementEventsSelect<true>;
    payload_affiliates: PayloadAffiliatesSelect<false> | PayloadAffiliatesSelect<true>;
    payload_affiliate_referrals: PayloadAffiliateReferralsSelect<false> | PayloadAffiliateReferralsSelect<true>;
    payload_affiliate_commissions: PayloadAffiliateCommissionsSelect<false> | PayloadAffiliateCommissionsSelect<true>;
    payload_partner_affiliates: PayloadPartnerAffiliatesSelect<false> | PayloadPartnerAffiliatesSelect<true>;
    payload_partner_applications: PayloadPartnerApplicationsSelect<false> | PayloadPartnerApplicationsSelect<true>;
    payload_partner_events: PayloadPartnerEventsSelect<false> | PayloadPartnerEventsSelect<true>;
    payload_billing_accounts: PayloadBillingAccountsSelect<false> | PayloadBillingAccountsSelect<true>;
    payload_subscriptions: PayloadSubscriptionsSelect<false> | PayloadSubscriptionsSelect<true>;
    payload_payments: PayloadPaymentsSelect<false> | PayloadPaymentsSelect<true>;
    payload_stripe_events: PayloadStripeEventsSelect<false> | PayloadStripeEventsSelect<true>;
    payload_billing_actions: PayloadBillingActionsSelect<false> | PayloadBillingActionsSelect<true>;
    payload_contacts: PayloadContactsSelect<false> | PayloadContactsSelect<true>;
    payload_crm_tags: PayloadCrmTagsSelect<false> | PayloadCrmTagsSelect<true>;
    payload_contact_tags: PayloadContactTagsSelect<false> | PayloadContactTagsSelect<true>;
    payload_contact_notes: PayloadContactNotesSelect<false> | PayloadContactNotesSelect<true>;
    payload_email_templates: PayloadEmailTemplatesSelect<false> | PayloadEmailTemplatesSelect<true>;
    payload_email_events: PayloadEmailEventsSelect<false> | PayloadEmailEventsSelect<true>;
    payload_admin_notifications: PayloadAdminNotificationsSelect<false> | PayloadAdminNotificationsSelect<true>;
    payload_member_groups: PayloadMemberGroupsSelect<false> | PayloadMemberGroupsSelect<true>;
    payload_spaces: PayloadSpacesSelect<false> | PayloadSpacesSelect<true>;
    payload_space_memberships: PayloadSpaceMembershipsSelect<false> | PayloadSpaceMembershipsSelect<true>;
    payload_space_posts: PayloadSpacePostsSelect<false> | PayloadSpacePostsSelect<true>;
    payload_space_comments: PayloadSpaceCommentsSelect<false> | PayloadSpaceCommentsSelect<true>;
    payload_space_files: PayloadSpaceFilesSelect<false> | PayloadSpaceFilesSelect<true>;
    payload_chat_threads: PayloadChatThreadsSelect<false> | PayloadChatThreadsSelect<true>;
    payload_chat_messages: PayloadChatMessagesSelect<false> | PayloadChatMessagesSelect<true>;
    payload_audit_events: PayloadAuditEventsSelect<false> | PayloadAuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: PayloadUser | PayloadMember;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PayloadUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_users".
 */
export interface PayloadUser {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'payload_users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_media".
 */
export interface PayloadMedia {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_pages".
 */
export interface PayloadPage {
  id: number;
  title: string;
  slug?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_posts".
 */
export interface PayloadPost {
  id: number;
  title: string;
  slug?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  categories?: (number | PayloadCategory)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_categories".
 */
export interface PayloadCategory {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Visual prototype only. Not connected to Stripe, WordPress, FluentCRM, or FluentCommunity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_courses".
 */
export interface PayloadCourse {
  id: number;
  /**
   * Marks this record as visual prototype data.
   */
  prototype?: boolean | null;
  /**
   * Stable identifier for local demo content.
   */
  prototypeKey?: string | null;
  title: string;
  slug: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | PayloadMedia;
  status: 'draft' | 'published' | 'archived';
  visibility: 'public' | 'members' | 'restricted';
  /**
   * Visual label only. This does not grant or enforce access.
   */
  accessBadge: 'free' | 'pro' | 'vip' | 'manual';
  estimatedDuration?: string | null;
  sortOrder?: number | null;
  showInPrototypeDashboard?: boolean | null;
  featured?: boolean | null;
  /**
   * Visual-only progress value for the prototype dashboard.
   */
  mockProgress?: number | null;
  prototypeNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ordered course sections for the visual prototype.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_course_modules".
 */
export interface PayloadCourseModule {
  id: number;
  prototype?: boolean | null;
  course: number | PayloadCourse;
  title: string;
  description?: string | null;
  sortOrder: number;
  publishedPreview?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Visual lesson content only. Progress and permissions are not persisted or enforced.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_lessons".
 */
export interface PayloadLesson {
  id: number;
  prototype?: boolean | null;
  module: number | PayloadCourseModule;
  title: string;
  slug: string;
  summary?: string | null;
  sortOrder: number;
  estimatedDuration?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videoProviderLabel?: ('none' | 'youtube' | 'vimeo' | 'mux' | 'other') | null;
  videoIdOrPreviewUrl?: string | null;
  downloads?: (number | PayloadMedia)[] | null;
  previewLesson?: boolean | null;
  /**
   * Visual-only completion state.
   */
  mockCompletionState?: ('not_started' | 'in_progress' | 'completed') | null;
  /**
   * Visual-only lock state. This is not authorization.
   */
  visualLockState?: ('available' | 'locked' | 'coming_soon') | null;
  prototypeNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Visual access examples only. No real member, billing, or entitlement data is connected.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_course_access_preview".
 */
export interface PayloadCourseAccessPreview {
  id: number;
  prototype?: boolean | null;
  displayLabel: string;
  type: 'free' | 'pro' | 'vip' | 'manual' | 'private';
  description?: string | null;
  badgeText?: string | null;
  exampleMemberName?: string | null;
  course?: (number | null) | PayloadCourse;
  visualState: 'available' | 'locked' | 'coming_soon';
  updatedAt: string;
  createdAt: string;
}
/**
 * Student and client accounts. This is separate from Payload administrator users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_members".
 */
export interface PayloadMember {
  id: number;
  accountStatus: 'pending' | 'active' | 'blocked' | 'suspended' | 'deleted';
  source: 'self_signup' | 'admin_created' | 'stripe_checkout' | 'migration';
  emailVerifiedAt?: string | null;
  billingHoldReason?: string | null;
  lastLoginAt?: string | null;
  lastLoginIp?: string | null;
  /**
   * Internal administrator notes. Do not show this to members.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'payload_members';
}
/**
 * Member profile details and communication preferences.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_member_profiles".
 */
export interface PayloadMemberProfile {
  id: number;
  member: number | PayloadMember;
  displayName: string;
  avatar?: (number | null) | PayloadMedia;
  timezone?: string | null;
  phone?: string | null;
  company?: string | null;
  marketingConsent?: boolean | null;
  transactionalEmailConsent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Member authentication and account-security events for administrator review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_member_security_events".
 */
export interface PayloadMemberSecurityEvent {
  id: number;
  member: number | PayloadMember;
  eventType:
    | 'account_created'
    | 'email_verified'
    | 'password_reset_requested'
    | 'password_changed'
    | 'billing_payment_failed'
    | 'billing_payment_recovered'
    | 'billing_payment_refunded'
    | 'billing_payment_disputed'
    | 'billing_dispute_resolved'
    | 'invitation_created'
    | 'invitation_consumed'
    | 'profile_changed'
    | 'email_change_requested'
    | 'email_changed'
    | 'login_failed'
    | 'account_blocked'
    | 'account_suspended'
    | 'account_restored'
    | 'account_deleted';
  source?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Digest-only, single-use member verification records. Plaintext tokens are never stored.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_member_verification_tokens".
 */
export interface PayloadMemberVerificationToken {
  id: number;
  member: number | PayloadMember;
  email: string;
  purpose:
    | 'member_email_verification'
    | 'member_invitation'
    | 'set_password'
    | 'password_reset'
    | 'email_change_confirmation';
  tokenDigest: string;
  expiresAt: string;
  consumedAt?: string | null;
  invalidatedAt?: string | null;
  lastSentAt?: string | null;
  sendAttempts: number;
  idempotencyKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private media used for protected lesson resources.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_private_media".
 */
export interface PayloadPrivateMedia {
  id: number;
  /**
   * Internal label for administrators. Private course files are not publicly linked.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Course file and protected resource records.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_lesson_resources".
 */
export interface PayloadLessonResource {
  id: number;
  title: string;
  lesson: number | PayloadLesson;
  /**
   * Public media fallback only. Do not use this field for confidential paid lesson files.
   */
  file?: (number | null) | PayloadMedia;
  /**
   * Use this for private paid lesson resources. Learners can only download it through the guarded route.
   */
  protectedFile?: (number | null) | PayloadPrivateMedia;
  status: 'draft' | 'published' | 'archived';
  /**
   * When true, runtime routes must confirm lesson access before serving the file.
   */
  downloadRequiresAccess?: boolean | null;
  sortOrder?: number | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Course enrollment projections from billing and manual grants.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_course_enrollments".
 */
export interface PayloadCourseEnrollment {
  id: number;
  /**
   * Human-readable label such as email + course. Keep stable for audit review.
   */
  displayName: string;
  member: number | PayloadMember;
  course: number | PayloadCourse;
  status: 'pending' | 'active' | 'completed' | 'revoked' | 'expired';
  source: 'manual' | 'stripe' | 'migration' | 'access_policy';
  startsAt?: string | null;
  expiresAt?: string | null;
  completedAt?: string | null;
  revokedAt?: string | null;
  revokedReason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Member lesson progress and completion state.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_lesson_progress".
 */
export interface PayloadLessonProgress {
  id: number;
  displayName: string;
  member: number | PayloadMember;
  lesson: number | PayloadLesson;
  status: 'not_started' | 'in_progress' | 'completed';
  startedAt?: string | null;
  completedAt?: string | null;
  percentComplete?: number | null;
  lastPositionSeconds?: number | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Member access groups used by course, community, and billing rules.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_access_groups".
 */
export interface PayloadAccessGroup {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'archived';
  groupType: 'manual' | 'plan' | 'cohort' | 'migration';
  /**
   * Manual group membership. Automated membership should be reflected through grants/events.
   */
  members?: (number | PayloadMember)[] | null;
  description?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Access policies that resolve whether a member may view a resource.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_access_policies".
 */
export interface PayloadAccessPolicy {
  id: number;
  name: string;
  status: 'draft' | 'active' | 'paused' | 'archived';
  resourceType: 'course' | 'lesson' | 'space' | 'access_group';
  /**
   * Target Payload document id. Kept as text so policies can cover multiple collection types.
   */
  resourceId: string;
  privacy: 'public' | 'members' | 'private' | 'secret';
  allowedPlans?: ('free' | 'exhibitor' | 'pro' | 'vip')[] | null;
  requiredGroups?: (number | PayloadAccessGroup)[] | null;
  /**
   * Fail-closed for private paid resources when billing status is not active or trialing.
   */
  requireActiveBilling?: boolean | null;
  allowPreviewLessons?: boolean | null;
  priority?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  notes?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Access grants issued directly or through group membership.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_access_grants".
 */
export interface PayloadAccessGrant {
  id: number;
  displayName: string;
  /**
   * Set this for a direct member grant. Leave empty for group grants.
   */
  member?: (number | null) | PayloadMember;
  /**
   * Set this for a group-level grant. Direct member grant takes precedence in audits.
   */
  accessGroup?: (number | null) | PayloadAccessGroup;
  resourceType: 'course' | 'lesson' | 'space' | 'access_group';
  resourceId: string;
  status: 'pending' | 'active' | 'revoked' | 'expired';
  source: 'manual' | 'stripe' | 'migration' | 'policy' | 'system';
  /**
   * External id such as Stripe subscription id, migration row id, or admin action id.
   */
  sourceId?: string | null;
  startsAt?: string | null;
  expiresAt?: string | null;
  revokedAt?: string | null;
  revokedReason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Entitlement audit trail for access decisions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_entitlement_events".
 */
export interface PayloadEntitlementEvent {
  id: number;
  displayName: string;
  member?: (number | null) | PayloadMember;
  eventType: 'access_evaluated' | 'access_granted' | 'access_revoked' | 'billing_hold_applied' | 'billing_hold_cleared';
  resourceType: 'course' | 'lesson' | 'space' | 'access_group';
  resourceId: string;
  result: 'allowed' | 'denied' | 'changed';
  reason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal referral programme records: affiliate members, referral codes, referral history, commission state, and payout review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_affiliates".
 */
export interface PayloadAffiliate {
  id: number;
  displayName: string;
  member: number | PayloadMember;
  referralCode: string;
  status: 'pending' | 'active' | 'suspended';
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal affiliate referral history and conversion state for the referral and commission programme.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_affiliate_referrals".
 */
export interface PayloadAffiliateReferral {
  id: number;
  displayName: string;
  affiliate: number | PayloadAffiliate;
  referredMember?: (number | null) | PayloadMember;
  status: 'tracked' | 'converted' | 'rejected';
  convertedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal affiliate commission rows, status, and administrator payout review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_affiliate_commissions".
 */
export interface PayloadAffiliateCommission {
  id: number;
  displayName: string;
  affiliate: number | PayloadAffiliate;
  referral: number | PayloadAffiliateReferral;
  amountMinor: number;
  currency: string;
  status: 'pending' | 'approved' | 'void';
  updatedAt: string;
  createdAt: string;
}
/**
 * External partner organizations and destinations: profiles, recipient emails, trusted destinations, webhook rules, and public partner application handoff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_partner_affiliates".
 */
export interface PayloadPartnerAffiliate {
  id: number;
  name: string;
  slug: string;
  status: 'draft' | 'active' | 'paused' | 'archived';
  category: string;
  summary?: string | null;
  logo?: string | null;
  applicationMode: 'redirect' | 'email' | 'webhook' | 'manual_export';
  affiliateUrl?: string | null;
  recipientEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  webhookEndpoint?: string | null;
  requiredFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  privacyNotice?: string | null;
  sortOrder?: number | null;
  externalReference?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public partner application history, delivery state, retries, export readiness, and operations handoff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_partner_applications".
 */
export interface PayloadPartnerApplication {
  id: number;
  displayName: string;
  member: number | PayloadMember;
  partner: number | PayloadPartnerAffiliate;
  status: 'submitted' | 'delivery_pending' | 'delivered' | 'delivery_failed';
  submittedAt?: string | null;
  deliveredAt?: string | null;
  applicationReference?: string | null;
  memberNameSnapshot?: string | null;
  memberEmailSnapshot?: string | null;
  memberPhoneSnapshot?: string | null;
  partnerSlugSnapshot?: string | null;
  partnerNameSnapshot?: string | null;
  companySnapshot?: string | null;
  countrySnapshot?: string | null;
  experienceSnapshot?: string | null;
  messageSnapshot?: string | null;
  consentAcceptedAt?: string | null;
  deliveryMethod: 'redirect' | 'email' | 'webhook' | 'manual_export';
  deliveryAttempts: number;
  lastDeliveryError?: string | null;
  trustedDestinationSnapshot?: string | null;
  source?: string | null;
  legacyWpUserId?: number | null;
  legacyReference?: string | null;
  internalNotes?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Partner delivery and application event history for external partner operations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_partner_events".
 */
export interface PayloadPartnerEvent {
  id: number;
  displayName: string;
  partner?: (number | null) | PayloadPartnerAffiliate;
  application?: (number | null) | PayloadPartnerApplication;
  member?: (number | null) | PayloadMember;
  eventType: string;
  sourceRoute?: string | null;
  status?: string | null;
  deliveryMethod?: ('redirect' | 'email' | 'webhook' | 'manual_export') | null;
  attempt?: number | null;
  deliveryError?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Billing account projections mirrored from Stripe and member actions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_billing_accounts".
 */
export interface PayloadBillingAccount {
  id: number;
  displayName: string;
  member: number | PayloadMember;
  stripeCustomerId: string;
  stripeMode: 'test' | 'live';
  billingStatus: 'none' | 'active' | 'trialing' | 'billing_hold' | 'past_due' | 'unpaid' | 'canceled';
  defaultPaymentMethodId?: string | null;
  billingEmail?: string | null;
  lastSyncedAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subscription projections and current access tier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_subscriptions".
 */
export interface PayloadSubscription {
  id: number;
  displayName: string;
  member: number | PayloadMember;
  billingAccount: number | PayloadBillingAccount;
  stripeSubscriptionId: string;
  stripePriceId?: string | null;
  stripeProductId?: string | null;
  plan: 'free' | 'exhibitor' | 'pro' | 'vip';
  status: 'incomplete' | 'incomplete_expired' | 'trialing' | 'active' | 'past_due' | 'canceled' | 'unpaid' | 'paused';
  cancelAtPeriodEnd?: boolean | null;
  currentPeriodStart?: string | null;
  currentPeriodEnd?: string | null;
  trialEndsAt?: string | null;
  canceledAt?: string | null;
  lastStripeEventId?: string | null;
  lastSyncedAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment history and refund/dispute projections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_payments".
 */
export interface PayloadPayment {
  id: number;
  displayName: string;
  member?: (number | null) | PayloadMember;
  subscription?: (number | null) | PayloadSubscription;
  stripeInvoiceId?: string | null;
  stripePaymentIntentId?: string | null;
  amount: number;
  currency: string;
  status: 'pending' | 'paid' | 'failed' | 'refunded' | 'disputed' | 'dispute_resolved' | 'voided';
  paidAt?: string | null;
  failedAt?: string | null;
  failureReason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_stripe_events".
 */
export interface PayloadStripeEvent {
  id: number;
  eventId: string;
  eventType: string;
  livemode: boolean;
  processingStatus: 'received' | 'processed' | 'deduped' | 'skipped' | 'failed';
  receivedAt: string;
  processedAt?: string | null;
  failureReason?: string | null;
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_billing_actions".
 */
export interface PayloadBillingAction {
  id: number;
  displayName: string;
  member?: (number | null) | PayloadMember;
  actionType:
    | 'checkout_completed'
    | 'subscription_created'
    | 'subscription_updated'
    | 'subscription_canceled'
    | 'payment_succeeded'
    | 'payment_failed'
    | 'payment_refunded'
    | 'payment_disputed'
    | 'dispute_resolved'
    | 'access_blocked'
    | 'access_restored';
  status: 'pending' | 'completed' | 'failed' | 'skipped';
  sourceEventId?: string | null;
  notes?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_contacts".
 */
export interface PayloadContact {
  id: number;
  email: string;
  member?: (number | null) | PayloadMember;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  lifecycleStage: 'lead' | 'student' | 'client' | 'partner' | 'churned';
  emailStatus: 'subscribed' | 'transactional_only' | 'unsubscribed' | 'bounced' | 'complained';
  marketingConsentAt?: string | null;
  lastActivityAt?: string | null;
  source?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_crm_tags".
 */
export interface PayloadCrmTag {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'archived';
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_contact_tags".
 */
export interface PayloadContactTag {
  id: number;
  displayName: string;
  contact: number | PayloadContact;
  tag: number | PayloadCrmTag;
  source: 'manual' | 'stripe' | 'course' | 'migration' | 'automation';
  sourceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_contact_notes".
 */
export interface PayloadContactNote {
  id: number;
  title: string;
  contact: number | PayloadContact;
  noteType: 'admin_note' | 'support' | 'billing' | 'course' | 'migration';
  body: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_email_templates".
 */
export interface PayloadEmailTemplate {
  id: number;
  name: string;
  templateKey: string;
  status: 'draft' | 'active' | 'archived';
  purpose:
    | 'account_created'
    | 'password_changed'
    | 'payment_made'
    | 'subscription_started'
    | 'subscription_canceled'
    | 'payment_failed'
    | 'admin_notification';
  subject: string;
  preheader?: string | null;
  textBody: string;
  htmlBody?: string | null;
  /**
   * When true, email workflows must also notify the configured admin recipient.
   */
  adminCopyRequired?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_email_events".
 */
export interface PayloadEmailEvent {
  id: number;
  displayName: string;
  toEmail: string;
  contact?: (number | null) | PayloadContact;
  templateKey: string;
  deliveryStatus:
    | 'queued'
    | 'sent'
    | 'delivered'
    | 'opened'
    | 'clicked'
    | 'bounced'
    | 'complained'
    | 'failed'
    | 'skipped';
  resendEmailId?: string | null;
  dedupeKey?: string | null;
  sentAt?: string | null;
  deliveredAt?: string | null;
  failureReason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_admin_notifications".
 */
export interface PayloadAdminNotification {
  id: number;
  title: string;
  notificationType: 'account' | 'billing' | 'course' | 'community' | 'system';
  severity: 'info' | 'warning' | 'error' | 'critical';
  status: 'unread' | 'read' | 'archived';
  body: string;
  relatedCollection?: string | null;
  relatedDocumentId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Member group records used by access and moderation workflows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_member_groups".
 */
export interface PayloadMemberGroup {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'archived';
  visibility: 'public' | 'private' | 'secret';
  members?: (number | PayloadMember)[] | null;
  description?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community spaces and their visibility rules.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_spaces".
 */
export interface PayloadSpace {
  id: number;
  name: string;
  slug: string;
  status: 'draft' | 'published' | 'archived';
  spaceType: 'discussion' | 'course_cohort' | 'announcement' | 'chat';
  visibility: 'public' | 'members' | 'private' | 'secret';
  requiredAccessGroups?: (number | PayloadAccessGroup)[] | null;
  linkedCourse?: (number | null) | PayloadCourse;
  description?: string | null;
  sortOrder?: number | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community membership records.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_space_memberships".
 */
export interface PayloadSpaceMembership {
  id: number;
  displayName: string;
  member: number | PayloadMember;
  space: number | PayloadSpace;
  role: 'member' | 'moderator' | 'admin';
  status: 'pending' | 'active' | 'muted' | 'blocked' | 'removed';
  joinedAt?: string | null;
  expiresAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community post records and moderation state.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_space_posts".
 */
export interface PayloadSpacePost {
  id: number;
  title: string;
  space: number | PayloadSpace;
  author: number | PayloadMember;
  postType: 'discussion' | 'question' | 'announcement';
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  moderationStatus: 'visible' | 'pending_review' | 'hidden' | 'deleted';
  pinned?: boolean | null;
  locked?: boolean | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_space_comments".
 */
export interface PayloadSpaceComment {
  id: number;
  displayName: string;
  post: number | PayloadSpacePost;
  author: number | PayloadMember;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  moderationStatus: 'visible' | 'pending_review' | 'hidden' | 'deleted';
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_space_files".
 */
export interface PayloadSpaceFile {
  id: number;
  title: string;
  space: number | PayloadSpace;
  uploadedBy: number | PayloadMember;
  post?: (number | null) | PayloadSpacePost;
  comment?: (number | null) | PayloadSpaceComment;
  attachmentType: 'document' | 'image' | 'external_video' | 'private_video';
  caption?: string | null;
  altText?: string | null;
  sortOrder?: number | null;
  externalProvider?: ('youtube' | 'vimeo') | null;
  externalMediaId?: string | null;
  bunnyVideoId?: string | null;
  bunnyLibraryId?: string | null;
  /**
   * Public media fallback only. Do not use this field for restricted community files.
   */
  file?: (number | null) | PayloadMedia;
  /**
   * Use this for restricted community files served only through the guarded member route.
   */
  protectedFile?: (number | null) | PayloadPrivateMedia;
  moderationStatus: 'visible' | 'pending_review' | 'hidden' | 'deleted';
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_chat_threads".
 */
export interface PayloadChatThread {
  id: number;
  title: string;
  space?: (number | null) | PayloadSpace;
  participants?: (number | PayloadMember)[] | null;
  status: 'open' | 'locked' | 'archived';
  lastMessageAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_chat_messages".
 */
export interface PayloadChatMessage {
  id: number;
  displayName: string;
  thread: number | PayloadChatThread;
  author: number | PayloadMember;
  body: string;
  moderationStatus: 'visible' | 'pending_review' | 'hidden' | 'deleted';
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Administrator-visible operational and security audit history.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_audit_events".
 */
export interface PayloadAuditEvent {
  id: number;
  displayName: string;
  actorType: 'admin' | 'member' | 'stripe' | 'system' | 'migration';
  actorId?: string | null;
  action: string;
  targetCollection: string;
  targetId?: string | null;
  severity: 'info' | 'warning' | 'critical';
  ipAddress?: string | null;
  userAgent?: string | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'payload_users';
        value: number | PayloadUser;
      } | null)
    | ({
        relationTo: 'payload_media';
        value: number | PayloadMedia;
      } | null)
    | ({
        relationTo: 'payload_pages';
        value: number | PayloadPage;
      } | null)
    | ({
        relationTo: 'payload_posts';
        value: number | PayloadPost;
      } | null)
    | ({
        relationTo: 'payload_categories';
        value: number | PayloadCategory;
      } | null)
    | ({
        relationTo: 'payload_courses';
        value: number | PayloadCourse;
      } | null)
    | ({
        relationTo: 'payload_course_modules';
        value: number | PayloadCourseModule;
      } | null)
    | ({
        relationTo: 'payload_lessons';
        value: number | PayloadLesson;
      } | null)
    | ({
        relationTo: 'payload_course_access_preview';
        value: number | PayloadCourseAccessPreview;
      } | null)
    | ({
        relationTo: 'payload_members';
        value: number | PayloadMember;
      } | null)
    | ({
        relationTo: 'payload_member_profiles';
        value: number | PayloadMemberProfile;
      } | null)
    | ({
        relationTo: 'payload_member_security_events';
        value: number | PayloadMemberSecurityEvent;
      } | null)
    | ({
        relationTo: 'payload_member_verification_tokens';
        value: number | PayloadMemberVerificationToken;
      } | null)
    | ({
        relationTo: 'payload_private_media';
        value: number | PayloadPrivateMedia;
      } | null)
    | ({
        relationTo: 'payload_lesson_resources';
        value: number | PayloadLessonResource;
      } | null)
    | ({
        relationTo: 'payload_course_enrollments';
        value: number | PayloadCourseEnrollment;
      } | null)
    | ({
        relationTo: 'payload_lesson_progress';
        value: number | PayloadLessonProgress;
      } | null)
    | ({
        relationTo: 'payload_access_groups';
        value: number | PayloadAccessGroup;
      } | null)
    | ({
        relationTo: 'payload_access_policies';
        value: number | PayloadAccessPolicy;
      } | null)
    | ({
        relationTo: 'payload_access_grants';
        value: number | PayloadAccessGrant;
      } | null)
    | ({
        relationTo: 'payload_entitlement_events';
        value: number | PayloadEntitlementEvent;
      } | null)
    | ({
        relationTo: 'payload_affiliates';
        value: number | PayloadAffiliate;
      } | null)
    | ({
        relationTo: 'payload_affiliate_referrals';
        value: number | PayloadAffiliateReferral;
      } | null)
    | ({
        relationTo: 'payload_affiliate_commissions';
        value: number | PayloadAffiliateCommission;
      } | null)
    | ({
        relationTo: 'payload_partner_affiliates';
        value: number | PayloadPartnerAffiliate;
      } | null)
    | ({
        relationTo: 'payload_partner_applications';
        value: number | PayloadPartnerApplication;
      } | null)
    | ({
        relationTo: 'payload_partner_events';
        value: number | PayloadPartnerEvent;
      } | null)
    | ({
        relationTo: 'payload_billing_accounts';
        value: number | PayloadBillingAccount;
      } | null)
    | ({
        relationTo: 'payload_subscriptions';
        value: number | PayloadSubscription;
      } | null)
    | ({
        relationTo: 'payload_payments';
        value: number | PayloadPayment;
      } | null)
    | ({
        relationTo: 'payload_stripe_events';
        value: number | PayloadStripeEvent;
      } | null)
    | ({
        relationTo: 'payload_billing_actions';
        value: number | PayloadBillingAction;
      } | null)
    | ({
        relationTo: 'payload_contacts';
        value: number | PayloadContact;
      } | null)
    | ({
        relationTo: 'payload_crm_tags';
        value: number | PayloadCrmTag;
      } | null)
    | ({
        relationTo: 'payload_contact_tags';
        value: number | PayloadContactTag;
      } | null)
    | ({
        relationTo: 'payload_contact_notes';
        value: number | PayloadContactNote;
      } | null)
    | ({
        relationTo: 'payload_email_templates';
        value: number | PayloadEmailTemplate;
      } | null)
    | ({
        relationTo: 'payload_email_events';
        value: number | PayloadEmailEvent;
      } | null)
    | ({
        relationTo: 'payload_admin_notifications';
        value: number | PayloadAdminNotification;
      } | null)
    | ({
        relationTo: 'payload_member_groups';
        value: number | PayloadMemberGroup;
      } | null)
    | ({
        relationTo: 'payload_spaces';
        value: number | PayloadSpace;
      } | null)
    | ({
        relationTo: 'payload_space_memberships';
        value: number | PayloadSpaceMembership;
      } | null)
    | ({
        relationTo: 'payload_space_posts';
        value: number | PayloadSpacePost;
      } | null)
    | ({
        relationTo: 'payload_space_comments';
        value: number | PayloadSpaceComment;
      } | null)
    | ({
        relationTo: 'payload_space_files';
        value: number | PayloadSpaceFile;
      } | null)
    | ({
        relationTo: 'payload_chat_threads';
        value: number | PayloadChatThread;
      } | null)
    | ({
        relationTo: 'payload_chat_messages';
        value: number | PayloadChatMessage;
      } | null)
    | ({
        relationTo: 'payload_audit_events';
        value: number | PayloadAuditEvent;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'payload_users';
        value: number | PayloadUser;
      }
    | {
        relationTo: 'payload_members';
        value: number | PayloadMember;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'payload_users';
        value: number | PayloadUser;
      }
    | {
        relationTo: 'payload_members';
        value: number | PayloadMember;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_users_select".
 */
export interface PayloadUsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_media_select".
 */
export interface PayloadMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_pages_select".
 */
export interface PayloadPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_posts_select".
 */
export interface PayloadPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  status?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_categories_select".
 */
export interface PayloadCategoriesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_courses_select".
 */
export interface PayloadCoursesSelect<T extends boolean = true> {
  prototype?: T;
  prototypeKey?: T;
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  coverImage?: T;
  status?: T;
  visibility?: T;
  accessBadge?: T;
  estimatedDuration?: T;
  sortOrder?: T;
  showInPrototypeDashboard?: T;
  featured?: T;
  mockProgress?: T;
  prototypeNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_course_modules_select".
 */
export interface PayloadCourseModulesSelect<T extends boolean = true> {
  prototype?: T;
  course?: T;
  title?: T;
  description?: T;
  sortOrder?: T;
  publishedPreview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_lessons_select".
 */
export interface PayloadLessonsSelect<T extends boolean = true> {
  prototype?: T;
  module?: T;
  title?: T;
  slug?: T;
  summary?: T;
  sortOrder?: T;
  estimatedDuration?: T;
  content?: T;
  videoProviderLabel?: T;
  videoIdOrPreviewUrl?: T;
  downloads?: T;
  previewLesson?: T;
  mockCompletionState?: T;
  visualLockState?: T;
  prototypeNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_course_access_preview_select".
 */
export interface PayloadCourseAccessPreviewSelect<T extends boolean = true> {
  prototype?: T;
  displayLabel?: T;
  type?: T;
  description?: T;
  badgeText?: T;
  exampleMemberName?: T;
  course?: T;
  visualState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_members_select".
 */
export interface PayloadMembersSelect<T extends boolean = true> {
  accountStatus?: T;
  source?: T;
  emailVerifiedAt?: T;
  billingHoldReason?: T;
  lastLoginAt?: T;
  lastLoginIp?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_member_profiles_select".
 */
export interface PayloadMemberProfilesSelect<T extends boolean = true> {
  member?: T;
  displayName?: T;
  avatar?: T;
  timezone?: T;
  phone?: T;
  company?: T;
  marketingConsent?: T;
  transactionalEmailConsent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_member_security_events_select".
 */
export interface PayloadMemberSecurityEventsSelect<T extends boolean = true> {
  member?: T;
  eventType?: T;
  source?: T;
  ipAddress?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_member_verification_tokens_select".
 */
export interface PayloadMemberVerificationTokensSelect<T extends boolean = true> {
  member?: T;
  email?: T;
  purpose?: T;
  tokenDigest?: T;
  expiresAt?: T;
  consumedAt?: T;
  invalidatedAt?: T;
  lastSentAt?: T;
  sendAttempts?: T;
  idempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_private_media_select".
 */
export interface PayloadPrivateMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_lesson_resources_select".
 */
export interface PayloadLessonResourcesSelect<T extends boolean = true> {
  title?: T;
  lesson?: T;
  file?: T;
  protectedFile?: T;
  status?: T;
  downloadRequiresAccess?: T;
  sortOrder?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_course_enrollments_select".
 */
export interface PayloadCourseEnrollmentsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  course?: T;
  status?: T;
  source?: T;
  startsAt?: T;
  expiresAt?: T;
  completedAt?: T;
  revokedAt?: T;
  revokedReason?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_lesson_progress_select".
 */
export interface PayloadLessonProgressSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  lesson?: T;
  status?: T;
  startedAt?: T;
  completedAt?: T;
  percentComplete?: T;
  lastPositionSeconds?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_access_groups_select".
 */
export interface PayloadAccessGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  groupType?: T;
  members?: T;
  description?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_access_policies_select".
 */
export interface PayloadAccessPoliciesSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  resourceType?: T;
  resourceId?: T;
  privacy?: T;
  allowedPlans?: T;
  requiredGroups?: T;
  requireActiveBilling?: T;
  allowPreviewLessons?: T;
  priority?: T;
  startsAt?: T;
  endsAt?: T;
  notes?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_access_grants_select".
 */
export interface PayloadAccessGrantsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  accessGroup?: T;
  resourceType?: T;
  resourceId?: T;
  status?: T;
  source?: T;
  sourceId?: T;
  startsAt?: T;
  expiresAt?: T;
  revokedAt?: T;
  revokedReason?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_entitlement_events_select".
 */
export interface PayloadEntitlementEventsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  eventType?: T;
  resourceType?: T;
  resourceId?: T;
  result?: T;
  reason?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_affiliates_select".
 */
export interface PayloadAffiliatesSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  referralCode?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_affiliate_referrals_select".
 */
export interface PayloadAffiliateReferralsSelect<T extends boolean = true> {
  displayName?: T;
  affiliate?: T;
  referredMember?: T;
  status?: T;
  convertedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_affiliate_commissions_select".
 */
export interface PayloadAffiliateCommissionsSelect<T extends boolean = true> {
  displayName?: T;
  affiliate?: T;
  referral?: T;
  amountMinor?: T;
  currency?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_partner_affiliates_select".
 */
export interface PayloadPartnerAffiliatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  category?: T;
  summary?: T;
  logo?: T;
  applicationMode?: T;
  affiliateUrl?: T;
  recipientEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  webhookEndpoint?: T;
  requiredFields?: T;
  privacyNotice?: T;
  sortOrder?: T;
  externalReference?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_partner_applications_select".
 */
export interface PayloadPartnerApplicationsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  partner?: T;
  status?: T;
  submittedAt?: T;
  deliveredAt?: T;
  applicationReference?: T;
  memberNameSnapshot?: T;
  memberEmailSnapshot?: T;
  memberPhoneSnapshot?: T;
  partnerSlugSnapshot?: T;
  partnerNameSnapshot?: T;
  companySnapshot?: T;
  countrySnapshot?: T;
  experienceSnapshot?: T;
  messageSnapshot?: T;
  consentAcceptedAt?: T;
  deliveryMethod?: T;
  deliveryAttempts?: T;
  lastDeliveryError?: T;
  trustedDestinationSnapshot?: T;
  source?: T;
  legacyWpUserId?: T;
  legacyReference?: T;
  internalNotes?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_partner_events_select".
 */
export interface PayloadPartnerEventsSelect<T extends boolean = true> {
  displayName?: T;
  partner?: T;
  application?: T;
  member?: T;
  eventType?: T;
  sourceRoute?: T;
  status?: T;
  deliveryMethod?: T;
  attempt?: T;
  deliveryError?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_billing_accounts_select".
 */
export interface PayloadBillingAccountsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  stripeCustomerId?: T;
  stripeMode?: T;
  billingStatus?: T;
  defaultPaymentMethodId?: T;
  billingEmail?: T;
  lastSyncedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_subscriptions_select".
 */
export interface PayloadSubscriptionsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  billingAccount?: T;
  stripeSubscriptionId?: T;
  stripePriceId?: T;
  stripeProductId?: T;
  plan?: T;
  status?: T;
  cancelAtPeriodEnd?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  trialEndsAt?: T;
  canceledAt?: T;
  lastStripeEventId?: T;
  lastSyncedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_payments_select".
 */
export interface PayloadPaymentsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  subscription?: T;
  stripeInvoiceId?: T;
  stripePaymentIntentId?: T;
  amount?: T;
  currency?: T;
  status?: T;
  paidAt?: T;
  failedAt?: T;
  failureReason?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_stripe_events_select".
 */
export interface PayloadStripeEventsSelect<T extends boolean = true> {
  eventId?: T;
  eventType?: T;
  livemode?: T;
  processingStatus?: T;
  receivedAt?: T;
  processedAt?: T;
  failureReason?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_billing_actions_select".
 */
export interface PayloadBillingActionsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  actionType?: T;
  status?: T;
  sourceEventId?: T;
  notes?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_contacts_select".
 */
export interface PayloadContactsSelect<T extends boolean = true> {
  email?: T;
  member?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  lifecycleStage?: T;
  emailStatus?: T;
  marketingConsentAt?: T;
  lastActivityAt?: T;
  source?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_crm_tags_select".
 */
export interface PayloadCrmTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_contact_tags_select".
 */
export interface PayloadContactTagsSelect<T extends boolean = true> {
  displayName?: T;
  contact?: T;
  tag?: T;
  source?: T;
  sourceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_contact_notes_select".
 */
export interface PayloadContactNotesSelect<T extends boolean = true> {
  title?: T;
  contact?: T;
  noteType?: T;
  body?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_email_templates_select".
 */
export interface PayloadEmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  templateKey?: T;
  status?: T;
  purpose?: T;
  subject?: T;
  preheader?: T;
  textBody?: T;
  htmlBody?: T;
  adminCopyRequired?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_email_events_select".
 */
export interface PayloadEmailEventsSelect<T extends boolean = true> {
  displayName?: T;
  toEmail?: T;
  contact?: T;
  templateKey?: T;
  deliveryStatus?: T;
  resendEmailId?: T;
  dedupeKey?: T;
  sentAt?: T;
  deliveredAt?: T;
  failureReason?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_admin_notifications_select".
 */
export interface PayloadAdminNotificationsSelect<T extends boolean = true> {
  title?: T;
  notificationType?: T;
  severity?: T;
  status?: T;
  body?: T;
  relatedCollection?: T;
  relatedDocumentId?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_member_groups_select".
 */
export interface PayloadMemberGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  visibility?: T;
  members?: T;
  description?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_spaces_select".
 */
export interface PayloadSpacesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  spaceType?: T;
  visibility?: T;
  requiredAccessGroups?: T;
  linkedCourse?: T;
  description?: T;
  sortOrder?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_space_memberships_select".
 */
export interface PayloadSpaceMembershipsSelect<T extends boolean = true> {
  displayName?: T;
  member?: T;
  space?: T;
  role?: T;
  status?: T;
  joinedAt?: T;
  expiresAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_space_posts_select".
 */
export interface PayloadSpacePostsSelect<T extends boolean = true> {
  title?: T;
  space?: T;
  author?: T;
  postType?: T;
  body?: T;
  moderationStatus?: T;
  pinned?: T;
  locked?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_space_comments_select".
 */
export interface PayloadSpaceCommentsSelect<T extends boolean = true> {
  displayName?: T;
  post?: T;
  author?: T;
  body?: T;
  moderationStatus?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_space_files_select".
 */
export interface PayloadSpaceFilesSelect<T extends boolean = true> {
  title?: T;
  space?: T;
  uploadedBy?: T;
  post?: T;
  comment?: T;
  attachmentType?: T;
  caption?: T;
  altText?: T;
  sortOrder?: T;
  externalProvider?: T;
  externalMediaId?: T;
  bunnyVideoId?: T;
  bunnyLibraryId?: T;
  file?: T;
  protectedFile?: T;
  moderationStatus?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_chat_threads_select".
 */
export interface PayloadChatThreadsSelect<T extends boolean = true> {
  title?: T;
  space?: T;
  participants?: T;
  status?: T;
  lastMessageAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_chat_messages_select".
 */
export interface PayloadChatMessagesSelect<T extends boolean = true> {
  displayName?: T;
  thread?: T;
  author?: T;
  body?: T;
  moderationStatus?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload_audit_events_select".
 */
export interface PayloadAuditEventsSelect<T extends boolean = true> {
  displayName?: T;
  actorType?: T;
  actorId?: T;
  action?: T;
  targetCollection?: T;
  targetId?: T;
  severity?: T;
  ipAddress?: T;
  userAgent?: T;
  before?: T;
  after?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}